---
- name: "[{{ check_binary }}] Check if binary exists"
  command: "which {{ check_binary }}"
  register: check_binary_result
  changed_when: false
  failed_when: false

- name: "[{{ check_binary }}] Compute `need_install` flag"
  set_fact:
    need_install: >-
      {{
        check_binary_result.rc != 0
        or
        (
          target_roles
          | intersect(force_roles | default('') | split(','))
          | length > 0
        )
      }}
