- hosts: localhost
  vars_files:
    - vars/vars.yml

  pre_tasks:
    - name: Check if vars/main.yml exists
      stat:
        path: vars/main.yml
      register: vars_main_file
    - name: Load vars/main.yml if exists
      include_vars:
        file: vars/main.yml
      when: vars_main_file.stat.exists

    - name: Gather service facts
      service_facts:
      tags: always

  roles:
    - role: me.nvim/core
      tags: [nvim_core, nvim]
    - role: me.nvim/lazyvim
      tags: [lazyvim]
    - role: me.font
      tags: [nvim, font]
    - role: me.fzf
      tags: [nvim, fzf]
    - role: me.dbclient
      tags: [nvim, dbclient]
    - role: me.treesitter
      tags: [nvim, treesitter]
    - role: me.tools/tectonic
      tags: [nvim, tectonic]
    - role: me.tools/mmdc
      tags: [nvim, mmdc]
    - role: me.tools/delta
      tags: [nvim, delta]

- import_playbook: playbook-tui.yml
  vars:
    github_arch: "{{ arch_map[ansible_architecture] }}"
