---
roles:
  - name: ansible.install-gcloud
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s
    version: latest

collections:
  - name: community.general
  - name: kubernetes.core
    version: ">=6.1.0"