theme="${DOTFILES_THEME:-gruvbox}"

if [[ "$theme" == "gruvbox" ]]; then
  POWERLEVEL9K_DIR_FOREGROUND='#ebdbb2'
  POWERLEVEL9K_DIR_BACKGROUND='#282828'
  POWERLEVEL9K_DIR_ANCHOR_FOREGROUND='#fabd2f'
  POWERLEVEL9K_DIR_ANCHOR_BACKGROUND='#282828'
  POWERLEVEL9K_DIR_SHORTENED_FOREGROUND='#ebdbb2'
  POWERLEVEL9K_DIR_SHORTENED_BACKGROUND='#282828'

  POWERLEVEL9K_BACKGROUND='#282828'
  POWERLEVEL9K_FOREGROUND='#ebdbb2'

  POWERLEVEL9K_TIME_FOREGROUND='#83a598'
  POWERLEVEL9K_USER_FOREGROUND='#fabd2f'
  POWERLEVEL9K_HOST_FOREGROUND='#b8bb26'
  POWERLEVEL9K_STATUS_FOREGROUND='#fb4934'
  POWERLEVEL9K_VCS_FOREGROUND='#282828'
fi
