---
- name: Test if helm need installation
  include_role:
    name: me.utils/check_install
  vars:
    check_binary: helm
    target_roles: [helm]

- name: Resolve the latest helm tag github_asset_name
  include_role:
    name: me.utils/github_release_resolver
  vars:
    github_repo: "helm/helm"
    github_asset_name: "dummy"
    github_release_tag: "latest"
  when: need_install

- name: Download Helm archive
  get_url:
    url: "https://get.helm.sh/helm-{{ github_latest_tag }}-linux-amd64.tar.gz"
    dest: "/tmp/helm.tar.gz"
    mode: "0644"
  when: need_install

- name: Extract Helm binary
  unarchive:
    src: "/tmp/helm.tar.gz"
    dest: /tmp/
    remote_src: true
  when: need_install

- name: Move Helm binary to /usr/local/bin
  command: mv /tmp/linux-amd64/helm /usr/local/bin/helm
  become: true
  when: need_install
