---
- name: Ensure namespace exists
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ monitoring_namespace }}"
    state: present

- name: Add Loki datasource ConfigMap for Grafana
  kubernetes.core.k8s:
    state: present
    namespace: "{{ monitoring_namespace }}"
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: grafana-datasources-loki
        labels:
          grafana_datasource: "1"
      data:
        loki.yaml: |
          apiVersion: 1
          datasources:
            - name: Loki
              type: loki
              access: proxy
              url: http://loki:3100
              isDefault: false
              version: 1
              jsonData: {}

- name: Add Prometheus Helm repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts
    state: present

- name: Add Grafana Helm repo
  kubernetes.core.helm_repository:
    name: grafana
    repo_url: https://grafana.github.io/helm-charts

- name: Update all Helm repos
  ansible.builtin.command: helm repo update
  changed_when: false

- name: Deploy kube-prometheus-stack
  kubernetes.core.helm:
    name: kube-prometheus-stack
    chart_ref: prometheus-community/kube-prometheus-stack
    namespace: "{{ monitoring_namespace }}"
    values: "{{ lookup('template', 'values-kps.yml.j2') | from_yaml }}"
    #wait: true

- name: Deploy Loki
  kubernetes.core.helm:
    name: loki
    chart_ref: grafana/loki
    namespace: "{{ monitoring_namespace }}"
    values: "{{ lookup('template', 'values-loki.yml.j2') | from_yaml }}"
    state: present

- name: Deploy Promtail
  kubernetes.core.helm:
    name: promtail
    chart_ref: grafana/promtail
    namespace: "{{ monitoring_namespace }}"
    values: "{{ lookup('template', 'values-promtail.yml.j2') | from_yaml }}"
