---
- name: Git global .gitignore
  community.general.git_config:
    name: core.excludesfile
    value: "{{ ansible_facts['env']['HOME'] }}/setup/.gitignore"
    scope: global

- name: Git text editor
  community.general.git_config:
    name: core.editor
    scope: global
    value: vim

- name: Git pull rebase
  community.general.git_config:
    name: pull.rebase
    scope: global
    value: true

- name: Git configure email
  when: var_git_email is defined and var_git_email != ''
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ var_git_email }}"

- name: Git configure username
  when: var_git_username is defined and var_git_username != ''
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ var_git_username }}"

# Delta
- name: Git delta pager
  community.general.git_config:
    name: core.pager
    scope: global
    value: delta

- name: Git interactive diff filter using delta
  community.general.git_config:
    name: interactive.diffFilter
    scope: global
    value: "delta --color-only"

- name: Git delta navigation
  community.general.git_config:
    name: delta.navigate
    scope: global
    value: true

- name: Git merge conflict style
  community.general.git_config:
    name: merge.conflictStyle
    scope: global
    value: zdiff3

  # git-lfs
- name: Test if git-lfs is installed
  command: which git-lfs
  register: test_git_lsf
  changed_when: false
  failed_when: false

- name: Resolve the latest lazygit tag github_asset_name
  include_role:
    name: me.utils/github_release_resolver
  vars:
    github_repo: "git-lfs/git-lfs"
    github_asset_name: "dummy"
    github_release_tag: "latest"
  when: test_git_lsf.rc != 0

- name: "[git-lfs] Fetch GitHub asset"
  include_role:
    name: me.utils/fetch_github_asset
  when: test_git_lsf.rc != 0
  vars:
    github_repo: "git-lfs/git-lfs"
    github_asset_name: "git-lfs-linux-amd64-{{ github_latest_tag }}.tar.gz"
    extract_archive: true
    tmp_dir: /tmp/git-lfs

- name: Install git-lfs
  become: true
  when: test_git_lsf.rc != 0
  command: /tmp/git-lfs/git-lfs-{{ github_latest_tag | regex_replace('^v', '') }}/install.sh
  args:
    chdir: /tmp/git-lfs/git-lfs-{{ github_latest_tag | regex_replace('^v', '') }}
