---
# tasks file for me.samba

- name: Test is samba is already configured
  shell: grep -c "BEGIN CONFIG FOR SOURCES" /etc/samba/smb.conf || true
  register: test_conf_grep

- name: Install samba
  become: true
  apt:
    name:
      - samba
    state: present

- name: Fetch current smbpasswd users
  become: true
  when: test_conf_grep.stdout == "0"
  command: /usr/bin/pdbedit -L
  register: pdb_users

- name: Create samba user with a password
  become: true
  when: test_conf_grep.stdout == "0" and pdb_users.stdout.find(var_samba_user) == -1
  command:
    cmd: "/usr/bin/smbpasswd -s -a {{ var_samba_user }}"
    stdin: |
      {{ var_samba_password }}
      {{ var_samba_password }}

- name: Configure samba
  become: true
  when: test_conf_grep.stdout == "0"
  blockinfile:
    state: present
    insertafter: EOF
    dest: /etc/samba/smb.conf
    marker_begin: "BEGIN CONFIG FOR SOURCES"
    marker_end: "END CONFIG FOR SOURCES"
    content: |
      [sources]
        path = /home/{{ var_samba_user }}/sources/
        comment = /home/{{ var_samba_user }}/sources/
        browseable = yes
        read only = no
        writable = yes
        directory mask = 0777
        create mask = 0777
        guest ok = yes
        map archive = no
        valid users = {{ var_samba_user }}
