---
- name: Test if tmux need installation
  include_role:
    name: me.utils/check_install
  vars:
    check_binary: tmux
    target_roles: [tmux]

- name: Resolve the latest tmux tag github_asset_name
  include_role:
    name: me.utils/github_release_resolver
  vars:
    github_repo: "tmux/tmux-builds"
    github_asset_name: "dummy"
    github_release_tag: "latest"
  when: need_install

- name: Install tmux
  include_role:
    name: me.utils/install_github_binary
  vars:
    github_repo: "tmux/tmux-builds"
    github_asset_name: "tmux-{{ github_latest_tag | regex_replace('^v', '') }}-linux-x86_64.tar.gz"
    binary_src_name: "tmux"
    binary_dest_name: "tmux"
    tmp_dir: "/tmp/tmux"
    delete_tmp_dir: true
    extract_archive: true
  when: need_install

- name: Set tpm directory
  set_fact:
    tpm_directory: "{{ ansible_facts['env']['HOME'] }}/.config/tmux/plugins/tpm"

- name: Install tmux and dependencies
  become: true
  apt:
    name:
      - cmake
    state: present
  when: need_install

- name: Install Tmux Plugin Manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ tpm_directory }}"
    update: true
    version: master
  when: need_install

- name: Ensure {{ ansible_facts['env']['HOME'] }}/.config/tmux/ exists
  file:
    path: "{{ ansible_facts['env']['HOME'] }}/.config/tmux"
    state: directory
    mode: "0755"
  when: need_install

- name: Copy tmux configuration
  ansible.posix.synchronize:
    src: ./files/tmux/
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/tmux/"
    recursive: true
  when: need_install

- name: Install tmux plugins
  command: "{{ tpm_directory }}/bin/install_plugins"
  changed_when: false
  failed_when: false
  when: need_install

- name: Clean tmux plugins
  command: "{{ tpm_directory }}/bin/clean_plugins"
  changed_when: false
  when: need_install

- name: Copy setup folder in ~/
  ansible.posix.synchronize:
    src: ./files/setup
    dest: "{{ ansible_facts['env']['HOME'] }}"
    recursive: true
  when: need_install
