---
- name: Test if gcloud need installation
  include_role:
    name: me.utils/check_install
  vars:
    check_binary: gcloud
    target_roles: [gcloud]

- name: Download gcloud
  get_url:
    url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-linux-x86_64.tar.gz
    dest: /tmp/gcloud.tar.gz
    mode: "0644"
  when: need_install

- name: Remove previous gcloud install
  become: true
  file:
    path: /opt/google-cloud-sdk
    state: absent
  when: need_install

- name: Extract
  become: true
  unarchive:
    src: /tmp/gcloud.tar.gz
    dest: /opt
    remote_src: true
  when: need_install

- name: Install kubectl via gcloud
  become: true
  when: need_install
  ansible.builtin.command: /opt/google-cloud-sdk/bin/gcloud components install kubectl --quiet
