---
- name: Test if terraform need installation
  include_role:
    name: me.utils/check_install
  vars:
    check_binary: terraform
    target_roles: [terraform]

- name: Resolve the latest terraform tag github_asset_name
  include_role:
    name: me.utils/github_release_resolver
  vars:
    github_repo: "hashicorp/terraform"
    github_asset_name: "dummy"
    github_release_tag: "latest"
  when: need_install

- name: "[terraform] Download and Extract"
  when: need_install
  include_role:
    name: me.utils/download_file
  vars:
    download_dir: "/tmp/terraform"
    download_url: "https://releases.hashicorp.com/terraform/{{ github_latest_tag | regex_replace('^v', '') }}/terraform_{{ github_latest_tag | regex_replace('^v', '') }}_linux_amd64.zip"
    filename: "terraform.zip"
    extract_archive: true

- name: Install terraform binary
  become: true
  copy:
    src: "/tmp/terraform/terraform"
    dest: "/usr/local/bin/terraform"
    mode: "0755"
  when: need_install

- name: Delete /tmp/git-lfs
  file:
    path: /tmp/git-lfs
    state: absent
