---
- name: Test if terraform need installation
  include_role:
    name: me.utils/check_install
  vars:
    check_binary: terraform
    target_roles: [terraform]

- name: Install the HashiCorp GPG key
  become: true
  when: need_install
  shell: |
    set -o pipefail
    wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
  args:
    executable: /bin/bash

- name: Add the official HashiCorp repository to your system
  become: true
  when: need_install
  shell: |
    set -o pipefail
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_lsb.codename | lower }} main" \
    | sudo tee /etc/apt/sources.list.d/hashicorp.list
  args:
    executable: /bin/bash

- name: Install terraform
  become: true
  when: need_install
  apt:
    name:
      - terraform
    update_cache: true
    state: present
