---
- name: Set default nvim config name
  set_fact:
    nvim_appname: "{{ lookup('env', 'NVIM_APPNAME') | default('nvim', true) }}"

# Delete nvim config
- name: Delete previous nvim config ({{ nvim_appname }})
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "~/.config/{{ nvim_appname }}"
    - "~/.local/share/{{ nvim_appname }}"
    - "~/.local/state/{{ nvim_appname }}"
    - "~/.cache/{{ nvim_appname }}"

# Install LazyVim
- name: Clone LazyVim
  git:
    repo: https://github.com/LazyVim/starter.git
    dest: "~/.config/{{ nvim_appname }}"
    depth: 1
    version: main
- name: Delete .git folder
  file:
    path: "~/.config/{{ nvim_appname }}/.git"
    state: absent

- name: Define LazyVim custom files
  set_fact:
    lazyvim_custom_files:
      - lua
      - snippets
      - mason-lock.json
      - stylua.toml

- name: Remove existing config entries
  file:
    path: "~/.config/{{ nvim_appname }}/{{ item }}"
    state: absent
  loop: "{{ lazyvim_custom_files }}"

- name: Create symlinks
  file:
    src: "{{ playbook_dir }}/files/nvim/lazyvim_config/{{ item }}"
    dest: "~/.config/{{ nvim_appname }}/{{ item }}"
    state: link
  loop: "{{ lazyvim_custom_files }}"
