---
- name: Test if fzf need installation
  include_role:
    name: me.utils/check_install
  vars:
    check_binary: fzf
    target_roles: [fzf]

- name: Download fzf binary
  when: need_install
  get_url:
    url: https://github.com/junegunn/fzf/releases/download/v0.66.1/fzf-0.66.1-linux_amd64.tar.gz
    dest: /tmp/fzf.tar.gz
    mode: "0644"

- name: Unarchive /tmp/fzf.tar.gz
  when: need_install
  become: true
  unarchive:
    src: /tmp/fzf.tar.gz
    dest: /usr/local/bin

- name: Delete /tmp/fzf.tar.gz
  file:
    path: /tmp/fzf.tar.gz
    state: absent
