{% raw -%}
### MANAGED BY ANSIBLE
### Do not edit this file — add your changes in ~/.zshrc.d/*.sh

### source sh files in .zshrc.d/early.d/ ###
for fsh in "$HOME/.zshrc.d/early.d/"*.{sh,zsh}(N); do
  . "$fsh"
done
unset -v fsh

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
    git
    docker
    docker-compose
    kubectl
    helm
    kube-ps1
    npm
    tmux
    golang
    terraform
    aws
    ansible
    gcloud
    ollama

    zsh-completions
    zsh-autosuggestions
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

command -v fzf >/dev/null && source <(fzf --zsh)

#export TERM=xterm-256color

############ PATH ##################
## GOLANG
export GOPATH="$HOME/go"
export GOROOT='/usr/local/go'
export PATH=$GOROOT/bin:$PATH
export PATH=$GOPATH/bin:$PATH
export PATH=$HOME/.local/bin:$PATH

export DOTFILES_THEME=gruvbox

############ ALIAS ##################
alias ws="cd ~/sources"
alias d="git diff"
alias ds="git diff --staged"
alias s="git status"
alias delMergedBr="git branch --merged | grep -Ev '(^\*|master$|main$|dev$|develop$)' | tee /dev/stderr | xargs -r git branch -d"
alias delMergedBrTest="git branch --merged | grep -Ev '(^\*|master$|main$|dev$|develop$)'"

alias dpsn="docker ps --format '{{.Names}}'"
alias dps='docker ps'

alias killDelve="ps aux | grep dlv | grep 'headless=true' | awk '{print $2}' | xargs kill"

alias eza="eza -a -l -g --total-size --icons=always --hyperlink"
alias bat="batcat"

### source sh files in .zshrc.d ###
for fsh in "$HOME/.zshrc.d/"*.{sh,zsh}(N); do
  . "$fsh"
done
unset -v fsh
{% endraw %}

