{% raw -%}
### MANAGED BY ANSIBLE
### Do not edit this file — add your changes in ~/.zshrc.d/*.sh

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
 source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="$HOME/.oh-my-zsh"

#ZSH_THEME="agnoster"
ZSH_THEME="powerlevel10k/powerlevel10k"


plugins=(
    git
    docker
    docker-compose
    kubectl
    helm
    kube-ps1
    npm
    tmux
    golang
    terraform
    aws
    ansible
    gcloud
    ollama

    zsh-completions
    zsh-autosuggestions
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# Customize the prompt by running `p10k configure` or editing `~/.p10k.zsh`
[[ -r ~/.p10k.zsh ]] && source ~/.p10k.zsh

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

command -v fzf >/dev/null && source <(fzf --zsh)

#export TERM=xterm-256color

############ PATH ##################
## GOLANG
export GOPATH="$HOME/go"
export GOROOT='/usr/local/go'
export PATH=$GOROOT/bin:$PATH
export PATH=$GOPATH/bin:$PATH
export PATH=$HOME/.local/bin:$PATH

export PATH="/opt/nvim/bin:$PATH"

############ ALIAS ##################
alias ws="cd ~/sources"
alias d="git diff"
alias ds="git diff --staged"
alias s="git status"
alias delMergedBr="git branch --merged | egrep -v '(^\*|master|main|dev|develop)' | xargs git branch -d"
alias delMergedBrTest="git branch --merged | egrep -v '(^\*|master|main|dev|develop)'"

alias dpsn="docker ps --format '{{.Names}}'"
alias dps='docker ps'

alias killDelve="ps aux | grep dlv | grep 'headless=true' | awk '{print $2}' | xargs kill"

alias eza="eza -a -l -g --total-size --icons=always --hyperlink"

### source sh files in .zshrc.d ###
mkdir -p "$HOME/.zshrc.d";
for fsh in $HOME/.zshrc.d/*.sh; do
    . "$fsh"
done
unset -v fsh
{% endraw %}

alias gituser1="git config --global user.email '{{ var_git_email }}'; git config --global user.name '{{ var_git_username }}'; git config --get user.name ; git config --get user.email"
