---
- name: Test if dbeaver is installed
  include_role:
    name: me.utils/check_install
  vars:
    check_binary: dbeaver-ce
    target_role: dbeaver

- name: Download dbeaver.deb
  when: need_install
  get_url:
    url: https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb
    dest: /tmp/dbeaver-ce_latest_amd64.deb
    mode: '0644'

- name: Install dbeaver
  when: need_install
  become: true
  apt:
    deb: /tmp/dbeaver-ce_latest_amd64.deb
    state: present

- name: Delete /tmp/dbeaver.deb
  when: need_install
  file:
    path: /tmp/dbeaver-ce_latest_amd64.deb
    state: absent
