# include kitty-themes/dexpota-kitty-themes/gruvbox_dark.conf
# include custom-themes/Gruvbox_Dark.conf
# include custom-themes/Kanagawa_dragon.conf
# include custom-themes/Tokyo_Night.conf
include custom-themes/Catppuccin-Mocha.conf

shell /usr/bin/zsh

font_family JetBrainsMono Nerd Font
font_size 11

dynamic_background_opacity yes
background_opacity 0.75

map ctrl+shift+f1 kitten toggle_opacity.py

# Remove window decorations (title bar + borders)
hide_window_decorations yes

confirm_os_window_close 0
remember_window_size no

enable_audio_bell no

map ctrl+shift+r no_op
map ctrl+shift+t no_op
map ctrl+shift+w no_op


#Toggle fullscreen
map ctrl+shift+f11 toggle_fullscreen
#map ctrl+cmd+f toggle_fullscreen 🍎
#Toggle maximized
map ctrl+shift+f10 toggle_maximized
# ctrl+Shift+f5 reload kitty config

# for macos
map cmd+k no_op
map cmd+l no_op
map cmd+f no_op
map cmd+n no_op
map cmd+t no_op
