---
- name: Test if lazygit need installation
  include_role:
    name: me.utils/check_install
  vars:
    check_binary: lazygit
    target_roles: [lazygit]

- name: Resolve the latest lazygit tag github_asset_name
  include_role:
    name: me.utils/github_release_resolver
  vars:
    github_repo: "jesseduffield/lazygit"
    github_asset_name: "dummy"
    github_release_tag: "latest"
  when: need_install

- name: Install lazygit
  include_role:
    name: me.utils/install_github_binary
  vars:
    github_repo: "jesseduffield/lazygit"
    github_asset_name: "lazygit_{{ github_latest_tag | regex_replace('^v', '') }}_linux_x86_64.tar.gz"
    binary_src_name: "lazygit"
    binary_dest_name: "lazygit"
    extract_archive: true
  when: need_install

- name: Copy config file
  copy:
    src: ./files/config.yml
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/lazygit/"
    mode: "0644"
